<?php

/**
 * @file
 * Code for the ft Slick Slider feature.
 */

include_once 'ft_slick_slider.features.inc';

function ft_slick_slider_theme_registry_alter(&$theme_registry) {
  // Defined path to the current module.
  $module_path = drupal_get_path('module', 'ft_slick_slider');
  // Find all .tpl.php files in this module's folder recursively.
  $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path . "/templates");
  // Iterate through all found template file objects.
  foreach ($template_file_objects as $key => $template_file_object) {
    // If the template has not already been overridden by a theme.
    if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
      // Alter the theme path and template elements.
      $theme_registry[$key]['theme path'] = $module_path;
      $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
      $theme_registry[$key]['type'] = 'module';
    }
  }
}

/**
 * Implements hook_preprocess_page().
 */
function ft_slick_slider_preprocess_page(&$variables) {
   $module_path = drupal_get_path('module', 'ft_slick_slider');
   drupal_add_css($module_path . '/css/ft_slick_slider.css');
}