name: Config Entity Source
description: Config entity source plugin for the Translation Management system.
package: Translation Management
core_version_requirement: ^8.8 || ^9
type: module

dependencies:
 - tmgmt:tmgmt
 - drupal:config_translation
 - drupal:block

# Information added by Drupal.org packaging script on 2020-06-02
version: '8.x-1.11'
project: 'tmgmt'
datestamp: 1591123644
