 <?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function odisean_layouts_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.odisean_layouts':
      return t('
        <h2>Odisean layouts for bootsrap4.</h2>
        <h3>Instructions</h3>
        <p>Just enable the module and you will see available the new templates</p>
      ');
  }
}
function odisean_layouts_theme($existing, $type, $theme, $path) {
  return [
    'custom_article' => [
      'variables' => ['test_var' => NULL], 
    ],
  ];
}