favicon:
  mimetype: image/jpeg
  path: 'public://favicon_logo_serra.jpg'
  use_default: false
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: 'public://logo_serra.png'
  use_default: false
