_core:
  default_config_hash: exRaKE0s6uZbfQrl_2WFEcTlc_1t81xEqCLuCCteUSk
langcode: es
minimum_single: 20
minimum_multiple: 20
disable_search_threshold: 0
minimum_width: 0
max_shown_results: null
use_relative_width: false
jquery_selector: 'select:visible'
search_contains: false
disable_search: false
allow_single_deselect: false
disabled_themes:
  bartik: '0'
  seven: '0'
  radix: '0'
  odisean: '0'
chosen_include: 0
placeholder_text_multiple: 'Elija algunas opciones'
placeholder_text_single: 'Elige una opción'
no_results_text: 'No hay resultados coincidentes'
