included_selectors: 'input, textarea'
excluded_selectors: ".node-form input\r\n.node-form textarea\r\n.node-form select\r\n.path-admin input\r\n.path-admin textarea"
required_indicator: append
_core:
  default_config_hash: fvvuim-Xfi2KRJiSVE9-Lj7cD6aDfjQxQ3Xnoe0TG18
langcode: es
